### PR TITLE
Update project to use Angular 14.2.12

### PR DESCRIPTION
**Pull request by miccou**
This PR is to update the project to use Angular 14.2.12.

### CODE REVIEW

**Comment by miccou** [comment]
@philenius please let me know if I missed anything.

**Comment by miccou** [comment]
@philenius appreciate you considering this PR.

**Comment by philenius** [comment]
@miccou thank you for your contribution, you're the hero :rocket:

**Comment by philenius** [comment]
v14.0.0 is now available on npmjs.org

**Pull request merged**
